version: '3.8'

services:
  cristiano-story:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - "coolify.managed=true"
      - "coolify.name=cristiano-story"
      - "coolify.version=1.0.0"
      - "coolify.type=application"

networks:
  coolify:
    external: true